name: burned
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.5.0
  build: ^2.0.1
  build_config: ^1.0.0
  source_gen: ^1.0.0
  burned_annotation:
    path:
      ../burned_annotation

dev_dependencies:
  test: ^1.14.4
